name = "tafy-demo"
#main = "functions/api/text2image.js"
pages_build_output_dir = "./.vercel/output/static"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_VERSION = "18"
#OPENAI_MODEL = "gpt-4-1106-preview"
OPENAI_MODEL = "gpt-4o"
USE_CLOUDFLARE = "yes"
CLOUDFLARE_AI_MODEL = "@hf/nousresearch/hermes-2-pro-mistral-7b"
CLOUDFLARE_TEXT2IMAGE_MODEL = "@cf/bytedance/stable-diffusion-xl-lightning"
WORKER_URL = "https://tafy-demo.tafy.workers.dev"
#DIETARY_PREFERENCES = "I don't like mushrooms, I'm allergic to peanuts, I'm a vegetarian, I'm a vegan, I'm lactose intolerant, I'm gluten intolerant, I'm on a low-carb diet, I'm on a low-fat diet, I'm on a low-sugar diet, I'm on a low-sodium diet, I'm on a low-calorie diet, I'm on a high-protein diet, I'm on a high-fiber diet, I'm on a keto diet, I'm on a paleo diet, I'm on a Mediterranean diet, I'm on a pescatarian diet, I'm on a flexitarian diet, I'm on a whole30 diet, I'm on a raw food diet, I'm on a clean eating diet, I'm on a weight loss diet, I'm on a weight gain diet, I'm on a muscle gain diet, I'm on a bodybuilding diet, I'm on a bulking diet, I'm on a cutting diet, I'm on a maintenance diet, I'm on a diabetic diet, I'm on a heart-healthy diet, I'm on a kidney-friendly diet, I'm on a liver-friendly diet, I'm on a thyroid-friendly diet, I'm on a PCOS-friendly diet, I'm on a menopause-friendly diet, I'm on a pregnancy-friendly diet, I'm on a breastfeeding-friendly diet, I'm on a baby-friendly diet, I'm on a toddler-friendly diet, I'm on a child-friendly diet, I'm on a teen-friendly diet, I'm on a senior-friendly diet, I'm on a student-friendly diet, I'm on a busy lifestyle diet, I'm on a sedentary lifestyle diet, I'm on an active lifestyle diet, I'm on an athletic lifestyle diet, I'm on a bodybuilder lifestyle diet, I'm on a vegan lifestyle diet, I'm on a vegetarian lifestyle diet, I'm on a pescatarian lifestyle diet, I'm on a flexitarian lifestyle diet, I'm on a paleo lifestyle diet, I'm on a keto lifestyle diet, I'm on a low-carb lifestyle diet, I'm on a low-fat lifestyle diet, I'm on a low-sugar lifestyle diet, I'm on a low-sodium lifestyle diet, I'm on a low-calorie lifestyle diet, I'm on a high-protein lifestyle diet, I'm on a high-fiber lifestyle diet."


#[[vectorize]]
#binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
#index_name = "recipe_idx"

[ai]
binding = "AI"

