name = "tafy-demo"
main = "functions/api/text2image.js"
#pages_build_output_dir = "./.vercel/output/static"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
CLOUDFLARE_TEXT2IMAGE_MODEL = "@cf/bytedance/stable-diffusion-xl-lightning"

#[[vectorize]]
#binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
#index_name = "recipe_idx"

[ai]
binding = "AI"


